version: '3.7'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - '.:/web'
      - '/web/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "8181:8181"
    command: npm run dev