# build environment
FROM node:13-alpine as build
WORKDIR /web
ENV PATH /web/node_modules/.bin:$PATH
COPY package.json /web/package.json
RUN npm install — silent
RUN npm install react-scripts@3.0.1 -g — silent
COPY . /web
RUN npm run build
# production environment
FROM nginx:1.16.0-alpine
COPY — from=build /web/build /usr/share/nginx/html
EXPOSE 80
CMD [“nginx”, “-g”, “daemon off;”]